# Greatest Works Game Server Configuration

# HTTP服务器配置
http:
  enabled: true
  addr: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576  # 1MB
  enable_cors: true
  enable_metrics: true
  enable_swagger: true
  enable_rate_limit: true
  rate_limit:
    requests_per_second: 100
    burst: 200
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "https://greatestworks.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    allow_credentials: true
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# TCP服务器配置
tcp:
  enabled: true
  addr: ":9090"
  max_connections: 10000
  read_timeout: 30s
  write_timeout: 30s
  buffer_size: 4096
  enable_compression: false
  heartbeat:
    enabled: true
    interval: 30s
    timeout: 10s
    max_missed: 3
  connection:
    keep_alive: true
    keep_alive_period: 30s
    no_delay: true



# 数据库配置
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "greatestworks"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
  migration:
    enabled: true
    path: "./migrations"

# Redis配置
redis:
  enabled: true
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 5m

# 日志配置
logging:
  level: "info"  # trace, debug, info, warn, error, fatal
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file:
    path: "./logs/server.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true
  fields:
    service: "greatestworks-server"
    version: "1.0.0"

# 监控配置
monitoring:
  enabled: true
  metrics:
    enabled: true
    path: "/metrics"
    namespace: "greatestworks"
  health:
    enabled: true
    path: "/health"
  profiling:
    enabled: false
    path: "/debug/pprof"

# 认证配置
auth:
  jwt:
    secret: "your-jwt-secret-key-change-this-in-production"
    issuer: "greatestworks"
    audience: "greatestworks-users"
    access_token_ttl: 1h
    refresh_token_ttl: 24h
  oauth:
    enabled: false
    providers:
      google:
        client_id: ""
        client_secret: ""
      github:
        client_id: ""
        client_secret: ""

# 游戏配置
game:
  world:
    max_players: 10000
    tick_rate: 20  # Hz
    save_interval: 5m
  battle:
    max_duration: 30m
    turn_timeout: 30s
    max_participants: 10
  economy:
    starting_gold: 1000
    daily_bonus: 100
    max_inventory_size: 100

# 缓存配置
cache:
  enabled: true
  default_ttl: 1h
  cleanup_interval: 10m
  max_size: 1000
  strategies:
    player_data:
      ttl: 30m
      max_size: 5000
    battle_data:
      ttl: 1h
      max_size: 1000
    static_data:
      ttl: 24h
      max_size: 100

# 消息队列配置
message_queue:
  enabled: false
  provider: "redis"  # redis, rabbitmq, kafka
  redis:
    addr: "localhost:6379"
    password: ""
    db: 1
  topics:
    player_events: "player.events"
    battle_events: "battle.events"
    system_events: "system.events"

# 文件存储配置
storage:
  provider: "local"  # local, s3, minio
  local:
    path: "./storage"
    max_file_size: 10485760  # 10MB
  s3:
    region: "us-east-1"
    bucket: "greatestworks-storage"
    access_key: ""
    secret_key: ""
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/json"

# 安全配置
security:
  rate_limiting:
    enabled: true
    global_limit: 1000  # requests per minute
    per_ip_limit: 100   # requests per minute
  ddos_protection:
    enabled: true
    threshold: 1000  # requests per minute
    ban_duration: 1h
  encryption:
    enabled: false
    algorithm: "AES-256-GCM"
    key: ""

# 开发配置
development:
  debug: false
  hot_reload: false
  mock_data: false
  test_mode: false
  profiling: false

# 生产配置
production:
  optimize: true
  compress_responses: true
  enable_caching: true
  log_requests: true
  hide_errors: true